name: Sphinx Build and Deploy

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true 

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: |
          uv sync --frozen --group=docs

      - name: Build Sphinx Documentation
        run: |
          uv run sphinx-build -b html docs build

      - name: Add .nojekyll file
        run: touch build/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
